trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# 1. Restaura todas as dependências do NuGet e do Entity Framework
- task: DotNetCoreCLI@2
  displayName: 'Recuperar os pacotes'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# 2. Compila todo o projeto para validar se existem erros de sintaxe ou de código
- task: DotNetCoreCLI@2
  displayName: 'Buildando o projeto'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'
